# Generated by Django 3.0.5 on 2020-04-23 03:41

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='extension',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/file/', validators=[books.validators.validate_file_extension]),
        ),
    ]
